### PR TITLE
SHOP-2375, SHOP-2376: Inject API version.

### PR DESCRIPTION
**Pull request by laithalissa**
Allow the PayPal API version to be injected in the driver constructor
so that we can easily roll back updates to PayPal API calls.

### CODE REVIEW

**Comment by giftig** [comment]
Hmm why not use django settings for the default API version?

**Comment by giftig** [comment]
Laith has convinced me that as the API version is tied into the code, it shouldn't be a setting, which seems logical to me.

This change looks good to me.

**Comment by DSmedley1989** [comment]
Looks okay to me also.

**Comment by giftig** [comment]
I'll wait and see if @leepa has any opinion before we get this merged

**Comment by giftig** [comment]
Lee's not around but this has two reviews so **Ship it**
Image of Yaktocat

**Pull request merged**
